Repository SofairOfficial/rust-repository-template, pull requests merged in 2023-03, with the labels that each got.

#7 Configure linting and formatting tools
  .clippy.toml
  .github/workflows/ci.yml
  .gitignore
  .rustfmt.toml
  .vscode/settings.json
  Cargo.toml
Labels: enhancement

#13 Creation of issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/task.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: platform: documentation, type: feature

#16 feat(service): implement a tiny greeter service
  .rustfmt.toml
  CONTRIBUTOR_BIBLE.md
  Cargo.toml
  crates/greeter_cli/Cargo.toml
  crates/greeter_cli/src/main.rs
  crates/greeter_service/Cargo.toml
  crates/greeter_service/src/lib.rs
  crates/greeter_service/src/service.rs
  crates/greeter_service/src/traits.rs
Labels: type: feature, status: in progress, priority: high, environment: testing

#20 test(mock): implement a tiny mocking example
  Cargo.toml
  crates/greeter_mock/Cargo.toml
  crates/greeter_mock/src/main.rs
  crates/greeter_mock/src/traits.rs
Labels: type: feature, priority: low, complexity: small

#22 Add a dependencies section in the GitHub task template
  .github/ISSUE_TEMPLATE/task.yml
Labels: status: in review, priority: low, complexity: small, environment: production
